#coding=cp936
Blocked              = "Blocked"
OpenInternet         = "Open Internet"
FullCone             = "Full Cone"
SymmetricUDPFirewall = "Symmetric UDP Firewall"
RestricNAT           = "Restric NAT"
RestricPortNAT       = "Restric Port NAT"
SymmetricNAT         = "Symmetric NAT"
Uncomplete           = "Uncomplete"